improved the bldapp script

diff --git a/bldapp b/bldapp
--- a/bldapp
+++ b/bldapp
@@ -8,6 +8,22 @@
 CC=gcc
 #CC=xlc_r
 
+if [ -z "$1" ]
+then
+  echo
+  echo "Usage: bldapp <prog_name (w/o ext)> [ <db_name> [ <userid> <password> ]]"
+  echo
+  exit
+fi
+
+if [ ! -f "${1}.sqc" ]
+then
+  echo
+  echo "ERROR: source file ${1}.sqc does not exist."
+  echo
+  exit 1
+fi
+
 # Set DB2PATH to where DB2 will be accessed.
 # The default is the standard instance path.
 DB2PATH=/home/db2inst1/sqllib
@@ -16,13 +32,13 @@ DB2PATH=/home/db2inst1/sqllib
 INCFILE=gchash.h
 echo "/* This file is automatically generated. */" >$INCFILE
 
-COMMIT_HASH=`git log -1 --pretty=%H`
+COMMIT_HASH=`git log -1 --pretty=%H ${1}.sqc`
 
 if [ "$?" == "0" ]
 then
   echo "" >>$INCFILE
   echo "#define COMMIT_HASH \"${COMMIT_HASH}\"" >>$INCFILE
-  COMMIT_HASH_ABBREV=`git log -1 --pretty=%h`
+  COMMIT_HASH_ABBREV=`git log -1 --pretty=%h ${1}.sqc`
   echo "#define COMMIT_HASH_ABBREV \"${COMMIT_HASH_ABBREV}\"" >>$INCFILE
 fi
 
